FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/source
RUN gcc -o bin2c bin2c.c
RUN mkdir -p /deps
RUN ldd /repo/source/bin2c | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/source/bin2c /repo/source/bin2c
ENV LD_LIBRARY_PATH=/deps
